# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  massproducer:
    build:
      context: "/home/ekrem/RiderProjects/ln-masstransit"
      dockerfile: "src/MassProducer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/ekrem/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/ekrem/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "massproducer:dev"
    ports:
    - "127.0.0.1:57024:57100"
    - "127.0.0.1:57224:57300"
    volumes:
    - "/home/ekrem/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/ekrem/RiderProjects/ln-masstransit/src/MassProducer:/app:rw"
    - "/home/ekrem/RiderProjects/ln-masstransit:/src:rw"
    - "/home/ekrem/.local/share/JetBrains/RiderRemoteDebugger/2023.2.2/Linux64:/riderDebugger"
    - "/home/ekrem/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/ekrem/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_18_20_26_53:/riderLogs:rw"
    working_dir: "/app"
  masstransit.consumer:
    build:
      context: "/home/ekrem/RiderProjects/ln-masstransit"
      dockerfile: "src/MassConsumer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/ekrem/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/ekrem/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "massconsumer:dev"
    ports:
    - "127.0.0.1:57025:57100"
    - "127.0.0.1:57225:57300"
    volumes:
    - "/home/ekrem/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/ekrem/RiderProjects/ln-masstransit/src/MassConsumer:/app:rw"
    - "/home/ekrem/RiderProjects/ln-masstransit:/src:rw"
    - "/home/ekrem/.local/share/JetBrains/RiderRemoteDebugger/2023.2.2/Linux64:/riderDebugger"
    - "/home/ekrem/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/ekrem/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_18_20_26_53:/riderLogs:rw"
    working_dir: "/app"
